version: '3'

services:
  elastic:
    image: elasticsearch:7.7.0
    environment:
      - cluster.name=movies-elasticsearch-cluster
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/
    ports:
      - "9200:9200"

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  movies_api:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis
      - elastic

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  etl:
     build: ./postgres_to_es
     env_file:
       - .env
     volumes:
       - etl_data:/srv/www/postgres_elastic/state
     depends_on:
       - db
       - elastic

volumes:
  elasticsearch_data:
  postgres_data:
  etl_data:
